packages:
  - apps/*
  - packages/*

catalog:
  "@eslint/js": ^9.39.2
  "@next/eslint-plugin-next": ^16.1.1
  "@next/third-parties": ^16.1.1
  "@radix-ui/react-slot": ^1.2.4
  "@tailwindcss/postcss": ^4.1.18
  "@turbo/gen": ^2.7.3
  "@types/node": ^25.0.3
  "@types/react": ^19.2.7
  "@types/react-dom": ^19.2.3
  "@typescript-eslint/eslint-plugin": ^8.52.0
  "@typescript-eslint/parser": ^8.52.0
  bumpp: ^10.3.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  czg: ^1.12.0
  eslint: ^9.39.2
  eslint-config-prettier: ^10.1.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-turbo: ^2.7.3
  globals: ^17.0.0
  lefthook: ^2.0.13
  lucide-react: ^0.562.0
  next: 16.1.1
  next-themes: ^0.4.6
  prettier: ^3.7.4
  react: 19.2.3
  react-dom: 19.2.3
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.18
  turbo: ^2.7.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.52.0
  zod: ^4.3.5
