packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.39.1
  '@next/eslint-plugin-next': ^16.0.7
  '@radix-ui/react-slot': ^1.2.4
  '@tailwindcss/postcss': ^4.1.17
  '@turbo/gen': ^2.6.3
  '@types/node': ^24.10.1
  '@types/react': ^19.2.7
  '@types/react-dom': ^19.2.3
  '@typescript-eslint/eslint-plugin': ^8.48.1
  '@typescript-eslint/parser': ^8.48.1
  bumpp: ^10.3.2
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  czg: ^1.12.0
  eslint: ^9.39.1
  eslint-config-prettier: ^10.1.8
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^7.0.1
  eslint-plugin-turbo: ^2.6.3
  globals: ^16.5.0
  lefthook: ^2.0.8
  lucide-react: ^0.556.0
  next: 16.0.7
  next-themes: ^0.4.6
  prettier: ^3.7.4
  react: 19.2.1
  react-dom: 19.2.1
  tailwind-merge: ^3.4.0
  tailwindcss: ^4.1.17
  turbo: ^2.6.3
  tw-animate-css: ^1.4.0
  typescript: ^5.9.3
  typescript-eslint: ^8.48.1
  zod: ^4.1.13
