packages:
  - "apps/*"
  - "packages/*"
catalog:
  '@release-it/bumper': ^7.0.5
  czg: ^1.11.1
  eslint: ^9.20.1
  lefthook: ^1.11.13
  prettier: ^3.5.1
  release-it: ^19.0.2
  turbo: ^2.4.2
  typescript: ^5.7.3