packages:
  - "apps/*"
  - "packages/*"
catalog:
  "@eslint/js": ^9.27.0
  "@next/eslint-plugin-next": ^15.1.7
  "@radix-ui/react-slot": ^1.1.2
  "@tailwindcss/postcss": ^4.0.8
  "@turbo/gen": ^2.4.2
  "@types/node": ^20
  "@types/react-dom": ^19
  "@types/react": ^19
  "@typescript-eslint/eslint-plugin": ^8.24.1
  "@typescript-eslint/parser": ^8.24.1
  bumpp: ^10.1.1
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  czg: ^1.11.1
  eslint-config-prettier: ^9.1.0
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react-hooks: ^5.1.0
  eslint-plugin-react: ^7.37.4
  eslint-plugin-turbo: ^2.4.2
  eslint: ^9.20.1
  globals: ^15.15.0
  lefthook: ^1.11.13
  lucide-react: ^0.475.0
  next-themes: ^0.4.4
  next: ^15.2.3
  prettier: ^3.5.1
  react-dom: ^19.0.0
  react: ^19.0.0
  tailwind-merge: ^3.0.1
  tailwindcss: ^4.0.8
  turbo: ^2.4.2
  tw-animate-css: ^1.2.4
  typescript-eslint: ^8.24.1
  typescript: ^5.7.3
  zod: ^3.24.2