packages:
  - apps/*
  - packages/*

catalog:
  '@eslint/js': ^9.30.1
  '@next/eslint-plugin-next': ^15.3.5
  '@radix-ui/react-slot': ^1.2.3
  '@tailwindcss/postcss': ^4.1.11
  '@turbo/gen': ^2.5.4
  '@types/node': ^24.0.12
  '@types/react': ^19.1.8
  '@types/react-dom': ^19.1.6
  '@typescript-eslint/eslint-plugin': ^8.36.0
  '@typescript-eslint/parser': ^8.36.0
  bumpp: ^10.2.0
  class-variance-authority: ^0.7.1
  clsx: ^2.1.1
  czg: ^1.11.2
  eslint: ^9.30.1
  eslint-config-prettier: ^10.1.5
  eslint-plugin-only-warn: ^1.1.0
  eslint-plugin-react: ^7.37.5
  eslint-plugin-react-hooks: ^5.2.0
  eslint-plugin-turbo: ^2.5.4
  globals: ^16.3.0
  lefthook: ^1.12.1
  lucide-react: ^0.525.0
  next: ^15.3.5
  next-themes: ^0.4.6
  prettier: ^3.6.2
  react: ^19.1.0
  react-dom: ^19.1.0
  tailwind-merge: ^3.3.1
  tailwindcss: ^4.1.11
  turbo: ^2.5.4
  tw-animate-css: ^1.3.5
  typescript: ^5.8.3
  typescript-eslint: ^8.36.0
  zod: ^4.0.2
